# Generated by Django 5.1.4 on 2025-01-10 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='restock',
            new_name='restock_threshold',
        ),
    ]
